name: Angular RX State Deploy

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [18.14]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install and build
      working-directory: ./
      run: npm install && npm run build-prod && cp dist/rx-state/index.html dist/rx-state/404.html

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: ./dist/rx-state

